spring:
  profiles:
    active: ${ext.profile}
  thymeleaf:
    cache: false
  messages:
    basename: messages/messages,labels/label
    cache-seconds: -1
    encoding: UTF-8
    fallbackToSystemLocale: false
  security:
    basic:
      enable: false
  datasource:
    initialize: false
server:
  servlet:
    context-path: /animal-management

